var TextSource = {

  // start text with a period and a space, otherwise TextBuilder won't be able to find the first sentence.

  discworld: ". Great A'Tuin the turtle comes, swimming slowly through the interstellar gulf, hydrogen frost on his ponderous limbs, his huge and ancient shell pocked with meteor craters. Through sea-sized eyes that are crusted with rheum and asteroid dust He stares fixedly at the Destination. In a brain bigger than a city, with geological slowness, He thinks only of the Weight. Most of the weight is of course accounted for by Berilia, Tubul, Great T'Phon and Jerakeen, the four giant elephants upon whose broad and startanned shoulders the disc of the World rests, garlanded by the long waterfall at its vast circumference and domed by the baby-blue vault of Heaven. Astropsychology has been, as yet, unable to establish what they think about. The Great Turtle was a mere hypothesis until the day the small and secretive kingdom of Krull, whose rim-most mountains project out over the Rimfall, built a gantry and pulley arrangement at the tip of the most precipitous crag and lowered several observers over the Edge in a quartzwindowed brass vessel to peer through the mist veils. The early astrozoologists, hauled back from their long dangle by enormous teams of slaves, were able to bring back much information about the shape and nature of A'Tuin and the elephants but this did not resolve fundamental questions about the nature and purpose of the universe. For example, what was Atuin's actual sex? This vital question, said the Astrozoologists with mounting authority, would not be answered until a larger and more powerful gantry was constructed for a deep-space vessel. In the meantime they could only speculate about the revealed cosmos. There was, for example, the theory that A'Tuin had come from nowhere and would continue at a uniform crawl, or steady gait, into nowhere, for all time. This theory was popular among academics. An alternative, favoured by those of a religious persuasion, was that A'Tuin was crawling from the Birthplace to the Time of Mating, as were all the stars in the sky which were, obviously, also carried by giant turtles. When they arrived they would briefly and passionately mate, for the first and only time, and from that fiery union new turtles would be born to carry a new pattern of worlds. This was known as the Big Bang hypothesis. Thus it was that a young cosmochelonian of the Steady Gait faction, testing a new telescope with which he hoped to make measurements of the precise albedo of Great A'Tuin's right eye, was on this eventful evening the first outsider to see the smoke rise hubward from the burning of the oldest city in the world. Later that night he became so engrossed in his studies he completely forgot about it. Nevertheless, he was the first.",

  storm: ". Nearly a thousand men died in the first seconds of the Iron Warriors’ initial bombardment of Jericho Falls spaceport. The battle barge Stonebreaker fired three salvoes of magma bombs into the desolate rocky slopes surrounding the spaceport, blasting vast chunks of rock hundreds of metres into the air and flattening almost all the torpedo silos in the mountains with unerring accuracy. Alarm sirens screamed and the spaceport’s weapon batteries rumbled into firing positions as their gunners desperately sought to acquire targets before being annihilated. A few hastily blessed torpedoes roared upwards through the orange sky on pillars of fiery smoke and powerful beams of laser energy stabbed through the perpetually cloudless heavens. More bombs fell, this time within the perimeter of Jericho Falls, demolishing buildings, gouging great craters and hurling enormous clouds of umber ash into the atmosphere. Flames from burning structures lit the smoke from within and bodies lay aflame in the wreckage of the shattered spaceport. Smashed aircraft littered the ground and more exploded as the heat from the fires cooked off their weapons and fuel tanks. Bombs slammed into the rockcrete, scything lethal fragments everywhere. Others smashed into the runways, cratering them and melting the honeycombed adamantium with the heat of a star. The Marauders and Lightnings out in the open took the worst of the barrage, pulverised by the force of the explosions. The noise and confusion were unbelievable; the sky was red with flames and black with smoke. Heavy las-fire blasted upwards. A number of shells impacted on the main hangar’s roof. Its armoured structure had absorbed the damage so far, though vast cracks now zigzagged across the reinforced walls and roof. The main runway was engulfed in flames, burning pools of jet fuel spewing thick black smoke that turned day into night. Hell had come to Hydra Cordatus.",

}
